"purpose":"search","ko":"	세부설명	","cn":"	详细说明	","jp":"	細部説明	","vn":"	giải thích chi tiết	"
"purpose":"search","ko":"	최소적재무게	","cn":"	最小装载重量	","jp":"	最小積載重量	","vn":"	trọng lượng tối thiểu	"
"purpose":"search","ko":"	최대적재무게	","cn":"	最大装载重量	","jp":"	最大積載重量	","vn":"	trọng lượng tải tối đa	"
"purpose":"search","ko":"	최소적재수량	","cn":"	最小装载数量	","jp":"	最小積載数量	","vn":"	lượng tải tối thiểu	"
"purpose":"search","ko":"	최대적재수량	","cn":"	最大装载数量	","jp":"	最大積載数量	","vn":"	lượng tải tối đa	"